-- Adds a rule_type column to alert_history so the Track record UI can break
-- down real outcome performance per alert strategy (e.g. stacked_imbalance
-- vs trapped_traders) instead of only a single aggregate across every rule.
--
-- Every alert ever recorded before this migration was generated by the
-- stacked_imbalance detector, since trapped_traders only just became a live
-- engine rule type - so backfilling existing rows to 'stacked_imbalance' is
-- a statement of fact, not a guess.
alter table public.alert_history
  add column if not exists rule_type text;

update public.alert_history
  set rule_type = 'stacked_imbalance'
  where rule_type is null;

alter table public.alert_history
  alter column rule_type set default 'stacked_imbalance';

alter table public.alert_history
  alter column rule_type set not null;

alter table public.alert_history
  add constraint alert_history_rule_type_check
  check (rule_type in ('stacked_imbalance', 'trapped_traders'));
